services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    env_file:
      - ./utility/stack.env
    ports:
      - 27017:27017

  backend:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./utility/stack.env
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - ./utility/stack.env
    stdin_open: true
    tty: true

  npm:
    build:
      context: .
      dockerfile: utility/npm.dockerfile
    volumes:
      - ./frontend:/frontend

volumes:
  mongodb:
