services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodb:/data/db
    env_file:
      - ./env/mongodb.env

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    # volumes:
    # - ./backend:/app
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  # frontend:
  # build: ./frontend
  # ports:
  #   - "3000:3000"
  # volumes:
  #   - ./frontend/src:/app/src
  # env_file:
  #   - ./env/frontend.env

volumes:
  mongodb:
