services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodb:/data/db
    env_file:
      - ./env/mongodb.env

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - ./env/frontend.env

volumes:
  mongodb:
