services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    env_file:
      - ./utility/mongo.env
    ports:
      - 4002:27017

  backend:
    build: ./backend
    ports:
      - 4001:8080
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BACKEND_URL=http://192.168.10.3:4001
        - VITE_API_FRONTEND_URL=http://192.168.10.3:4000
    ports:
      - 4000:80
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    tty: true

  npm:
    build:
      context: .
      dockerfile: utility/npm.dockerfile
    volumes:
      - ./frontend:/frontend

volumes:
  mongodb:
